version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/streamlit/_stcore/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - evstockmaster-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - evstockmaster-network

networks:
  evstockmaster-network:
    driver: bridge
